/********************************************************************************
** Form generated from reading UI file 'ytframelessdlg.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_YTFRAMELESSDLG_H
#define UI_YTFRAMELESSDLG_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_YtFrameLessDlg
{
public:
    QGridLayout *gridLayout_2;
    QWidget *TitleWidget;
    QGridLayout *gridLayout_4;
    QPushButton *btnClose;
    QLabel *labelLogo;
    QPushButton *btnMin;
    QSpacerItem *horizontalSpacer;
    QPushButton *btnMax;
    QLabel *labelTitle;
    QPushButton *btnTooltip;
    QGridLayout *gridLayout;

    void setupUi(QDialog *YtFrameLessDlg)
    {
        if (YtFrameLessDlg->objectName().isEmpty())
            YtFrameLessDlg->setObjectName(QString::fromUtf8("YtFrameLessDlg"));
        YtFrameLessDlg->resize(809, 460);
        YtFrameLessDlg->setStyleSheet(QString::fromUtf8("QWidget #Widget,#Dialog,#YtFrameLessDlg,#MainDlg{\n"
"background-color: rgba(68, 74, 88, 150);\n"
"border: 1px solid rgb(40, 39, 57);\n"
"color: rgb(221, 221, 221);\n"
"font: 10pt \"Segoe UI\";\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"/*QToolTip*/\n"
"QToolTip {\n"
"	color: #ffffff;\n"
"	background-color: rgba(33, 37, 43, 180);\n"
"	border: 1px solid rgb(44, 49, 58);\n"
"	border-radius: 3px;\n"
"	font:bold 16pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	background-image: none;\n"
"	background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"	/*border-left: 2px solid rgb(255, 121, 198);*/\n"
"	border-left: 2px solid rgb(255, 0, 0);\n"
"	text-align: left;\n"
"	padding-left: 8px;\n"
"	margin: 0px;\n"
"}\n"
"\n"
"/*QMenu*/\n"
"QMenu\n"
"{\n"
"    color:#f1f1f1;\n"
"	font:bold 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	background-color: rgba(68, 74, 88, 150);\n"
"	border-radius: 6px; \n"
"}\n"
"QMenu::item\n"
"{\n"
"    color:rgb(255,255,255);\n"
"	padding-left:3px"
                        ";\n"
"	padding-right:2px;\n"
"	height:30px;\n"
"	border:1px solid #f1f1f1;\n"
"    border-left:2px solid #81bf5f;\n"
"}\n"
"QMenu::item:selected\n"
"{\n"
"	border:2px solid #579abe;\n"
"}\n"
"\n"
"QLabel{\n"
"color:#f1f1f1;\n"
"font:bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QLabel#LabelMessage{\n"
"color:#f1f1f1;\n"
"font:bold 16pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QLabel#labelTitle{\n"
"font:bold 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color:#f1f1f1;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"/*QLineEdit*/\n"
"QLineEdit {\n"
"color:#f1f1f1;\n"
"font:bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border: 1px solid #f1f1f1;\n"
"border-radius: 3px;\n"
"}\n"
"QLineEdit::hover{\n"
"border:1px solid #579abe;\n"
"}\n"
"QLineEdit:pressed{\n"
"border:1px solid #579abe;\n"
"}\n"
""
                        "QLineEdit:disabled{\n"
"border:2px solid #6f6f6f;\n"
"color: rgb(217, 225, 219);\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"/*QTextEdit*/\n"
"QTextEdit{\n"
"	color:#f1f1f1;\n"
"	font:bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	background: transparent;\n"
"	border: 1px solid #f1f1f1;\n"
"	border-radius: 3px;\n"
"}\n"
"\n"
"QTextEdit::disabled{\n"
"	color:#f1f1f1;\n"
"	font:bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	background: transparent;\n"
"	border: 2px solid #6f6f6f;\n"
"	border-radius: 3px;\n"
"}\n"
"\n"
"QTextEdit::hover{\n"
"border:1px solid #579abe;\n"
"}\n"
"QTextEdit:pressed{\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"/*QGroupBox*/\n"
"QGroupBox {\n"
"font:bold 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color:#f1f1f1;\n"
"border: 1px solid #f1f1f1;\n"
"margin-top:3ex;\n"
"border-radius: 3px;\n"
"/*padding-top:10px;*/\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"padding:0 3px;\n"
"}\n"
"\n"
"/*SpinBox*/\n"
""
                        "QSpinBox {\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: #f1f1f1;\n"
"color: #f1f1f1;\n"
"font: 75 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSpinBox::disabled {\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: #6f6f6f;\n"
"color: #f1f1f1;\n"
"font: 75 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSpinBox::hover {\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"QSpinBox::press {\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {   \n"
"image: url(:/btnicon/image/btnicon/up_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QSpinBox::up-arrow::disabled {   \n"
"image: url(:/btnicon/image/btnicon/up_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"image: url(:/btnicon/image/btnicon/down_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QSpinBox::down-arrow::disabled {\n"
"image: url(:/btnicon/ima"
                        "ge/btnicon/down_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: top right;\n"
"border-radius: 3px;\n"
"width: 35px;\n"
"border-width: 1px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: bottom right;\n"
"border-radius: 3px;\n"
"width: 35px;\n"
"border-width: 1px;\n"
"border-top-width: 0;\n"
"}\n"
"\n"
"/*Double SpinBox*/\n"
"QDoubleSpinBox {\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: #f1f1f1;\n"
"color: #f1f1f1;\n"
"font: 75 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::disabled {\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: #6f6f6f;\n"
"color: #f1f1f1;\n"
"font: 75 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"background: transparent;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::hover {\n"
"border:1px solid #579abe;\n"
"}\n"
""
                        "\n"
"QDoubleSpinBox::press {\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {   \n"
"image: url(:/btnicon/image/btnicon/up_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow::disabled {   \n"
"image: url(:/btnicon/image/btnicon/up_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"image: url(:/btnicon/image/btnicon/down_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow::disabled {\n"
"image: url(:/btnicon/image/btnicon/down_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"border-radius: 3px;\n"
"width: 35px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-radius: 3px;\n"
"width: 35px;\n"
"}\n"
"\n"
"/*QComboBox*/\n"
"QComboBox {\n"
"background-color: transparent;\n"
"border-style: solid; \n"
"border-width: 1px; \n"
"border-radius: 3px; \n"
"border-color: #f1f1f1; \n"
"font: bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\""
                        ";\n"
"color: #f1f1f1;\n"
"}\n"
"\n"
"QComboBox::disabled {\n"
"background-color: transparent;\n"
"border-style: solid; \n"
"border-width: 2px; \n"
"border-radius: 2px; \n"
"border-color: #6f6f6f; \n"
"font: bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color: #f1f1f1;\n"
"}\n"
"\n"
"QComboBox::hover{\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"QComboBox::press{\n"
"border:1px solid #579abe;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"background-color: #579abe;\n"
"border-style: outset; \n"
"border-width: 1px; \n"
"border-radius: 6px; \n"
"border-color: gray;\n"
"font:  13px;\n"
"color:#f1f1f1;\n"
"padding-left: 5px; \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"width: 22px;\n"
"border-left-width: 1px;\n"
"border-left-color: #1e1d23;\n"
"border-top-right-radius: 12px; /* same radius as the QComboBox */\n"
"border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"image: url(:/btnicon/image/btnicon/dow"
                        "n_enable.png);\n"
"width: 20px;\n"
"padding-right:10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow::disabled {\n"
"image: url(:/btnicon/image/btnicon/down_disable.png);\n"
"width: 20px;\n"
"}\n"
"\n"
"/*QTimeEdit*/\n"
"QTimeEdit,QDateEdit,QDateTimeEdit{\n"
"background-color: transparent;\n"
"border-style: solid; \n"
"border-width: 1px; \n"
"border-radius: 3px; \n"
"border-color: #f1f1f1; \n"
"font: bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color: #f1f1f1;\n"
"}\n"
"\n"
"QTimeEdit::disabled,QDateEdit::disabled,QDateTimeEdit::disabled{\n"
"background-color: transparent;\n"
"border-style: solid; \n"
"border-width: 2px; \n"
"border-radius: 3px; \n"
"border-color: #6f6f6f; \n"
"font: bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color: #f1f1f1;\n"
"}\n"
"\n"
"QTimeEdit::up-arrow,QDateEdit::up-arrow,QDateTimeEdit::up-arrow {   \n"
"image: url(:/btnicon/image/btnicon/up_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QTimeEdit::up-arrow::disabled,QDateEdit::up-arrow::disabled,QDate"
                        "TimeEdit::up-arrow::disabled {   \n"
"image: url(:/btnicon/image/btnicon/up_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow,QDateEdit::down-arrow,QDateTimeEdit::down-arrow {\n"
"image: url(:/btnicon/image/btnicon/down_enable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow::disabled,QDateEdit::down-arrow:disabled,QDateTimeEdit::down-arrow::disabled {\n"
"image: url(:/btnicon/image/btnicon/down_disable.png);\n"
"width:18;\n"
"}\n"
"\n"
"QTimeEdit::up-button,QDateEdit::up-button,QDateTimeEdit::up-button {\n"
"subcontrol-origin: border;\n"
"border-radius: 5px;\n"
"width: 35px;\n"
"}\n"
"\n"
"QTimeEdit::down-button,QDateEdit::down-button,QDateTimeEdit::down-button {\n"
"subcontrol-origin: border;\n"
"border-radius: 5px;\n"
"width: 35px;\n"
"}\n"
"\n"
"/*QPushButton*/\n"
"QPushButton{\n"
"width:transparent;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"padding: 2px;\n"
"font: bold 12pt;\n"
"background-color: #579abe;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton::default{\n"
"	bo"
                        "rder-style: solid;\n"
"	border-top-color: #579abe;\n"
"	border-right-color: #579abe;\n"
"	border-left-color: #579abe;\n"
"	border-bottom-color: #579abe;\n"
"	border-width: 1px;\n"
"	color: #a9b7c6;\n"
"	padding: 2px;\n"
"	background-color: #579abe;\n"
"}\n"
"QPushButton:hover{\n"
"	border-style: solid;\n"
"	border-top-color: #f1f1f1;\n"
"	border-right-color: #f1f1f1;\n"
"	border-left-color: #f1f1f1;\n"
"	border-bottom-color: #f1f1f1;\n"
"	border-bottom-width: 1px;\n"
"	border-style: solid;\n"
"	color: #f1f1f1;\n"
"	padding-bottom: 2px;\n"
"	background-color: #579abe;\n"
"}\n"
"QPushButton:pressed{\n"
"	border-style: solid;\n"
"	border-top-color: #f1f1f1;\n"
"	border-right-color: #f1f1f1;\n"
"	border-left-color: #f1f1f1;\n"
"	border-bottom-color: #f1f1f1;\n"
"	border-bottom-width: 2px;\n"
"	border-style: solid;\n"
"	color: #e67e22;\n"
"	padding-bottom: 1px;\n"
"	background-color: #579abe;\n"
"}\n"
"QPushButton:disabled{\n"
"	border-style: solid;\n"
"	border-top-color: transparent;\n"
"	border-right-color: trans"
                        "parent;\n"
"	border-left-color: transparent;\n"
"	border-bottom-color: transparent;\n"
"	border-bottom-width: 2px;\n"
"	border-style: solid;\n"
"	color: #808086;\n"
"	padding-bottom: 1px;\n"
"	background-color: #afd7e3;\n"
"}\n"
"QPushButton#btnMin,#btnMax,#btnClose,#btnTooltip{\n"
"background-color:transparent;\n"
"}\n"
"\n"
"/*QTableWidget*/\n"
"QTableWidget{\n"
"color: #f1f1f1;\n"
"background-color: transparent;\n"
"font: bold 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"border:1px solid #f1f1f1;\n"
"gridline-color: rgb(77, 134, 190);\n"
"border-radius: 3px; \n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    color: #f1f1f1;\n"
"}\n"
"\n"
"QTableWidget::item:hover{\n"
"	border:1px solid #f1f1f1;\n"
"}\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
"    color: #f1f1f1;\n"
"    border:1px solid #f1f1f1;\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"/*\345\267\246\344\270\212\350\247\222\345\205\250\351\200\211\346\214\211\351\222\256\350\203\214\346\231\257\350\211\262*/\n"
"QTableCornerBu"
                        "tton::section{\n"
"	background-color:transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"	background-color:transparent;\n"
"	margin:0px;\n"
"	color:#f1f1f1;\n"
"	font: 700 10pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	border:1px solid #579abe;\n"
"}\n"
"\n"
"QHeaderView::section:hover{\n"
"    border:1px solid #f1f1f1;\n"
"}\n"
"\n"
"QHeaderView::section:selected {\n"
"	background-color:#579abe;\n"
"	margin:0px;\n"
"	color:#f1f1f1;\n"
"	font: 700 12pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	border:2px solid #f1f1f1;\n"
"}\n"
"\n"
"/*QListWidget*/\n"
"QListWidget\n"
"{\n"
"color:#f1f1f1;\n"
"border:1px solid #f1f1f1;\n"
"background-color: rgb(30, 29, 35);\n"
"font: bold 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"border-radius: 3px; \n"
"}\n"
"/**\345\210\227\350\241\250\351\241\271*/\n"
"QListWidget::item\n"
"{\n"
"    color:rgb(200,200,200);\n"
"    height:40px;\n"
"    padding-left:20px;\n"
"    border:0px solid gray;\n"
"}\n"
"/**\345\210\227\350\241"
                        "\250\351\241\271\346\211\253\350\277\207*/\n"
"QListWidget::item:hover\n"
"{\n"
"    color:#f1f1f1;\n"
"    background:rgb(77, 134, 190);\n"
"   \n"
"}\n"
"/**\345\210\227\350\241\250\351\241\271\351\200\211\344\270\255*/\n"
"QListWidget::item::selected:active\n"
"{ \n"
"    color:#f1f1f1;\n"
"    background:rgb(77, 134, 190);\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    color:#f1f1f1;\n"
"    background:rgb(77, 134, 190);\n"
"}\n"
"\n"
"/*QTabWidget*/\n"
"QTabWidget {\n"
"color:#f1f1f1;\n"
"background-color: transparent;\n"
"border: 1px solid #f1f1f1;\n"
"border-radius: 3px; \n"
"}\n"
"\n"
"QTabWidget::pane{\n"
"	border:1px solid #f1f1f1;\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"QTabBar\n"
"{\n"
"    left: 5px; /* move to the right by 5px */\n"
"    border-radius: 3px;\n"
"	border:1px solid #f1f1f1;\n"
"    color: #f1f1f1;\n"
"    font: bold 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"QTabBar:focus\n"
"{\n"
"    border: 1px tran"
                        "sparent #f1f1f1;\n"
"}\n"
"\n"
"/* TOP TABS */\n"
"QTabBar::tab:top {\n"
"    border: 0px solid #f1f1f1;\n"
"    border-bottom: 0px transparent;\n"
"    background-color: #579abe;\n"
"    padding: 5px;\n"
"    min-width: 100px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"/* BOTTOM TABS */\n"
"QTabBar::tab:bottom {\n"
"    border: 0px solid #f1f1f1;\n"
"    border-bottom: 0px transparent;\n"
"    background-color: #579abe;\n"
"    padding: 5px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"/* LEFT TABS */\n"
"QTabBar::tab:left {\n"
"    border: 0px solid #f1f1f1;\n"
"    border-bottom: 0px transparent;\n"
"    background-color: #579abe;\n"
"    padding: 5px;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-height: 100px;\n"
"}\n"
"\n"
"/* RIGHT TABS */\n"
"QTabBar::tab:right {\n"
"    border: 0px solid #f1f1f1;\n"
"    border-bottom: 0px transparent;"
                        "\n"
"    background-color: #579abe;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-left-radius: 2px;\n"
"    min-height: 100px;\n"
"}\n"
"\n"
"/*\346\262\241\346\234\211\351\200\211\344\270\255\347\232\204tab*/\n"
"QTabBar::tab:!selected\n"
"{\n"
"    background-color: #6f6f6f;\n"
"	color:#f1f1f1;\n"
"}\n"
"\n"
"/*TreeWidget*/\n"
"QTreeWidget{\n"
"	color:#f1f1f1;\n"
"	background-color: transparent;\n"
"	border: 1px solid #f1f1f1;\n"
"	border-radius: 3px; \n"
"}\n"
"\n"
"/*TreeView*/\n"
"QTreeView{\n"
"	color:#f1f1f1;\n"
"	background-color: transparent;\n"
"	border: 1px solid #f1f1f1;\n"
"	border-radius: 3px; \n"
"}\n"
"\n"
"/*ListView*/\n"
"QListView{\n"
"	color:#f1f1f1;\n"
"	background-color: transparent;\n"
"	border: 1px solid #f1f1f1;\n"
"	border-radius: 3px; \n"
"}\n"
"\n"
"/*TableView*/\n"
"QTableView{\n"
"	color:#f1f1f1;\n"
"	background-color: transparent;\n"
"	border: 1px solid #f1f1f1;\n"
"	border-radius: 3px; \n"
"}\n"
"\n"
"/*\351\274\240\346\240\207\346\202\254\345\201"
                        "\234\345\234\250\346\262\241\346\234\211\351\200\211\344\270\255\347\232\204tab\344\270\212*/\n"
"QTabBar::tab:!selected:hover {\n"
"    color: white;\n"
"    border:2px solid #f1f1f1;\n"
"}\n"
"\n"
"QAbstractScrollArea\n"
"{\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"/*Check Box*/\n"
"QCheckBox{\n"
"font: 75 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:enabled:unchecked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/cb_close.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:enabled:checked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/cb_open.png);\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled:unchecked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/cb_close_disable.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled:checked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/cb_open_disable.png);\n"
"}\n"
"\n"
"/*RadioButton*/\n"
""
                        "QRadioButton{\n"
"font: 75 11pt \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"color: #ffffff;\n"
"}\n"
"QRadioButton::indicator:enabled:unchecked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/radio_unselect_enable.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:enabled:checked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/radio_select_enable.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled:unchecked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/radio_unselect_disable.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled:checked\n"
"{\n"
"width: 50px;height: 30px;\n"
"image: url(:/btnicon/image/btnicon/radio_select_disable.png);\n"
"}\n"
"\n"
"QScrollBar:vertical{ \n"
"    width:8px;  \n"
"    border-style:flat;\n"
"    border-radius: 4px;\n"
"    border:0px;\n"
"     background: #19191A;\n"
"} \n"
"QScrollBar::handle:vertical{ \n"
"    background: rgba(255,255,255,0.50);\n"
"    border-radius: 4px;\n"
"   "
                        " width:8px; \n"
"    min-height:91px; \n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::handle:vertical::hover{ \n"
"    background: rgba(255,255,255,0.90);\n"
"    border-radius: 4px;\n"
"    width:8px; \n"
"}\n"
"QScrollBar::handle:vertical::pressed{ \n"
"    background: rgba(255,255,255,0.90);\n"
"    border-radius:4px;\n"
"    width:8px; \n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #19191A;\n"
"border-style:flat;\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"   background: #19191A;\n"
"border-style:flat;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"   background: #19191A;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   background: #19191A;\n"
"}\n"
"QScrollBar:horizontal{ \n"
"    height:8px;  \n"
"    border-style:flat;\n"
"    border-radius: 4px;\n"
"    border:0px;\n"
"background: #19191A;\n"
"} \n"
"QScrollBar::handle:horizontal{ \n"
"    background: rgba(255,255,255,0.50);\n"
"    border-radius: 4px;\n"
"    height:8px; \n"
"    min-width:91px; \n"
"    border-style:flat;\n"
"}\n"
""
                        "QScrollBar::handle:horizontal::hover{ \n"
"    background: rgba(255,255,255,0.90);\n"
"    border-radius: 4px;\n"
"    height:8px; \n"
"}\n"
"QScrollBar::handle:horizontal::pressed{ \n"
"    background: rgba(255,255,255,0.90);\n"
"    border-radius:4px;\n"
"    height:8px; \n"
"}\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #19191A;\n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::add-page:horizontal {\n"
"   background: #19191A;\n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   background: #19191A;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"   background: #19191A;\n"
"}\n"
"\n"
"QFrame{\n"
"background-color: transparent;\n"
"color: rgb(87, 154, 190);\n"
"}\n"
""));
        gridLayout_2 = new QGridLayout(YtFrameLessDlg);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        gridLayout_2->setSizeConstraint(QLayout::SetFixedSize);
        gridLayout_2->setHorizontalSpacing(3);
        gridLayout_2->setVerticalSpacing(6);
        gridLayout_2->setContentsMargins(6, 6, 6, 6);
        TitleWidget = new QWidget(YtFrameLessDlg);
        TitleWidget->setObjectName(QString::fromUtf8("TitleWidget"));
        TitleWidget->setMinimumSize(QSize(0, 30));
        TitleWidget->setMaximumSize(QSize(16777215, 30));
        TitleWidget->setBaseSize(QSize(0, 0));
        TitleWidget->setStyleSheet(QString::fromUtf8(""));
        gridLayout_4 = new QGridLayout(TitleWidget);
        gridLayout_4->setSpacing(6);
        gridLayout_4->setObjectName(QString::fromUtf8("gridLayout_4"));
        gridLayout_4->setContentsMargins(0, 0, 0, 0);
        btnClose = new QPushButton(TitleWidget);
        btnClose->setObjectName(QString::fromUtf8("btnClose"));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btnClose->sizePolicy().hasHeightForWidth());
        btnClose->setSizePolicy(sizePolicy);
        btnClose->setMaximumSize(QSize(30, 30));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/btnicon/image/btnicon/close_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnClose->setIcon(icon);

        gridLayout_4->addWidget(btnClose, 0, 6, 1, 1);

        labelLogo = new QLabel(TitleWidget);
        labelLogo->setObjectName(QString::fromUtf8("labelLogo"));
        labelLogo->setMinimumSize(QSize(30, 30));
        labelLogo->setMaximumSize(QSize(30, 30));

        gridLayout_4->addWidget(labelLogo, 0, 0, 1, 1);

        btnMin = new QPushButton(TitleWidget);
        btnMin->setObjectName(QString::fromUtf8("btnMin"));
        sizePolicy.setHeightForWidth(btnMin->sizePolicy().hasHeightForWidth());
        btnMin->setSizePolicy(sizePolicy);
        btnMin->setMaximumSize(QSize(30, 30));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/btnicon/image/btnicon/min_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnMin->setIcon(icon1);

        gridLayout_4->addWidget(btnMin, 0, 4, 1, 1);

        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        gridLayout_4->addItem(horizontalSpacer, 0, 2, 1, 1);

        btnMax = new QPushButton(TitleWidget);
        btnMax->setObjectName(QString::fromUtf8("btnMax"));
        sizePolicy.setHeightForWidth(btnMax->sizePolicy().hasHeightForWidth());
        btnMax->setSizePolicy(sizePolicy);
        btnMax->setMaximumSize(QSize(30, 30));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/btnicon/image/btnicon/max_new.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnMax->setIcon(icon2);
        btnMax->setCheckable(false);

        gridLayout_4->addWidget(btnMax, 0, 5, 1, 1);

        labelTitle = new QLabel(TitleWidget);
        labelTitle->setObjectName(QString::fromUtf8("labelTitle"));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(labelTitle->sizePolicy().hasHeightForWidth());
        labelTitle->setSizePolicy(sizePolicy1);
        labelTitle->setMaximumSize(QSize(16777215, 30));

        gridLayout_4->addWidget(labelTitle, 0, 1, 1, 1);

        btnTooltip = new QPushButton(TitleWidget);
        btnTooltip->setObjectName(QString::fromUtf8("btnTooltip"));
        sizePolicy.setHeightForWidth(btnTooltip->sizePolicy().hasHeightForWidth());
        btnTooltip->setSizePolicy(sizePolicy);
        btnTooltip->setMaximumSize(QSize(30, 30));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/btnicon/image/btnicon/about.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnTooltip->setIcon(icon3);

        gridLayout_4->addWidget(btnTooltip, 0, 3, 1, 1);


        gridLayout_2->addWidget(TitleWidget, 0, 0, 1, 1);

        gridLayout = new QGridLayout();
        gridLayout->setSpacing(0);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setSizeConstraint(QLayout::SetFixedSize);

        gridLayout_2->addLayout(gridLayout, 1, 0, 1, 1);

        gridLayout_2->setRowStretch(1, 1);
        gridLayout_2->setRowMinimumHeight(1, 1);

        retranslateUi(YtFrameLessDlg);

        QMetaObject::connectSlotsByName(YtFrameLessDlg);
    } // setupUi

    void retranslateUi(QDialog *YtFrameLessDlg)
    {
        YtFrameLessDlg->setWindowTitle(QCoreApplication::translate("YtFrameLessDlg", "Dialog", nullptr));
        btnClose->setText(QString());
        labelLogo->setText(QString());
        btnMin->setText(QString());
        btnMax->setText(QString());
        labelTitle->setText(QCoreApplication::translate("YtFrameLessDlg", "TextLabel", nullptr));
        btnTooltip->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class YtFrameLessDlg: public Ui_YtFrameLessDlg {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_YTFRAMELESSDLG_H
